[package]
name = "catscii"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
pretty-hex = "0.4.1"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
